dist: 'xenial'
language: node_js
node_js:
  - '8'
before_install:
  - echo "Installing additional dependencies required for running tests on travis"
  - npm run cirequirements
before_script:
  - echo "Installing dev dependencies required of all codegens"
  - npm run deepinstall dev
script:
   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'
